const CACHE='benny-web-experiment-v28';
const SHELL=['./','./index.html','./apps/tools/tools.json','./apps/games/games.json','./shared/usage-analytics.js','./shared/extension-client.js','./shared/tool-gate.js','./shared/web-data.js','./shared/web-tool.css','./shared/web-tool-ui.js','./shared/scan-manager.js','./shared/voice-manager.js','./shared/ios-audio-fix.js','./extension-setup.html','./setup.js','./data-settings.html','./data-settings.js','./pwa.js','./manifest.webmanifest','./images/BeaminBenny.png','./images/narbefoundation.png','./images/pwa-192.png','./images/pwa-512.png','./images/favicon-16.png','./images/favicon-32.png','./images/apple-touch-icon.png',...['dayhub','journal','streaming'].map(x=>'./images/tools/'+x+'.png'),...['dayhub/index.html','dayhub/app.js','dayhub/style.css','dayhub/day-services.js','journal/index.html','journal/app.js','journal/style.css','journal/predictions.js','journal/questions.json','streaming/index.html','streaming/app.js','streaming/style.css','streaming/web-streaming.js','streaming/keyboard_integration.js','streaming/predictions.js','streaming/editor.html','streaming/editor.js','streaming/editor-files.js','streaming/metadata-config.js','streaming/tmdb-logo.svg','streaming/data.json','streaming/episodes.json'].map(x=>'./apps/tools/'+x)];
SHELL.push('./companion-setup.css','./companion-privacy.html','./apps/tools/journal/journal-look.css','./apps/tools/journal/calendar-view.js',...['index.html','style.css','app.js','predictions.js','web_keyboard_predictions.json'].map(x=>'./apps/tools/keyboard/'+x));
SHELL.push(...['playback-links.js','library-merge.js','quick-add.js','quick-add.css','collections/index.json',...['netflix','disney','hulu','prime','tubi','youtube'].map(s=>'collections/'+s+'-starter.json')].map(x=>'./apps/tools/streaming/'+x));
SHELL.push(...['services.js', 'episode-editor.js', 'episode-editor.css', 'logos/netflix-com.ico', 'logos/disneyplus-com.ico', 'logos/hulu-com.png', 'logos/primevideo-com.ico', 'logos/hbomax-com.ico', 'logos/paramountplus-com.ico', 'logos/pluto-tv.ico', 'logos/plex-tv.png', 'logos/youtube-com.ico', 'logos/tv-apple-com.png', 'logos/peacocktv-com.ico', 'logos/tubitv-com.png', 'logos/crunchyroll-com.png', 'logos/therokuchannel-roku-com.ico'].map(x=>'./apps/tools/streaming/'+x));
SHELL.push(...['platform.js','scan-settings.js','choice-scan.js','choice-scan-adapter.js','scan-status-badge.js','scan-status-badge.css'].map(x=>'./shared/'+x));
const allowed=new Set(SHELL.map(p=>new URL(p,self.registration.scope).href));
self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(SHELL)).then(()=>self.skipWaiting())));
self.addEventListener('activate',e=>e.waitUntil((async()=>{for(const key of await caches.keys())if(key.startsWith('benny-web-experiment-')&&key!==CACHE)await caches.delete(key);await self.clients.claim();})()));
self.addEventListener('fetch',e=>{
  // Cache only named, public, same-origin static assets. Never cache API/feed/media responses.
  if(e.request.method!=='GET'||!allowed.has(e.request.url))return;
  e.respondWith((async()=>{try{const r=await fetch(e.request);if(r.ok){const c=await caches.open(CACHE);await c.put(e.request,r.clone()).catch(()=>{});}return r;}catch{const cached=await caches.match(e.request);return cached||new Response('Offline. Open this tool once while connected.',{status:503});}})());
});
