// Canvas menu policy is shared; moving enemies, targeting and stomp cadence remain native.
(function(){
 const status=document.createElement('div');status.id='classic-scan-status';status.hidden=true;status.style.cssText='display:none;position:fixed;inset:0 0 auto;height:40px;z-index:5;pointer-events:none';document.body.append(status);let adapter,syncing=false,heldSpace=false,heldEnter=false,braking=false,cancelSpace=false,lastAuto=NarbeScanManager.getSettings().autoScan,lastState=null;
 const rawSpeak=speak,rawSelect=selectAction,rawForward=scanForward,rawBack=scanBackward;
 function describe(){let labels;if(gameState==='MENU')labels=['Play Game','Instructions','Settings','Exit Game'];else if(gameState==='INSTRUCTIONS')labels=['Back'];else if(gameState==='PAUSED')labels=['Continue','Restart Level','Settings','Main Menu'];else if(gameState==='SETTINGS'){const s=NarbeScanManager.getSettings();labels=['TTS: '+(tts_enabled?'ON':'OFF'),'Auto Scan: '+(s.autoScan?'ON':'OFF'),'Scan Speed: '+NarbeScanManager.getScanInterval()/1000+'s','Auto Stomp: '+(auto_stomp_enabled?'ON':'OFF'),'SFX: '+(sfx_enabled?'ON':'OFF'),'Music: '+(music_enabled?'ON':'OFF'),'Back']}else if(gameState==='CONFIRM_EXIT')labels=['Cancel','Proceed'];else if(gameState==='BUY')return{key:'BUY',statusHost:status,items:getVisibleBuyOptions().map(index=>({id:'BUY:'+index,index,label:index<buy_menu_options.length?buy_menu_options[index].name:['Start Level','Undo','Main Menu'][index-buy_menu_options.length]}))};else return null;return{key:gameState,statusHost:status,items:labels.map((label,index)=>({id:gameState+':'+index,label,index}))}}
 function fit(show){status.hidden=!show;status.style.display=show?'flex':'none';canvas.style.position=show?'fixed':'';canvas.style.top=show?'40px':'';canvas.style.height=show?'calc(100vh - 40px)':'';canvas.style.width=show?'100vw':''}
 function sync(){if(syncing)return;syncing=true;try{const d=describe();adapter.setInputHeld(heldEnter||heldSpace&&!braking);const fresh=lastState!==gameState;lastState=gameState;adapter.sync(d,{fresh});if(!d)fit(false)}finally{syncing=false}}
 adapter=NarbeChoiceScanAdapter.create({holdThreshold:3000,stateHost:document.body,speak:rawSpeak,onHighlight(item,s){menu_selected_index=item?.index??-1;fit(s.parked)},onSelect(){rawSelect();sync()}});
 scanForward=()=>{sync();if(adapter.active)adapter.step(1);else rawForward()};scanBackward=()=>{sync();if(adapter.active)adapter.step(-1);else rawBack()};selectAction=()=>{sync();if(adapter.active)adapter.select();else rawSelect()};speak=text=>{sync();return adapter.active?adapter.announce(text):rawSpeak(text)};
 for(const name of ['enter_store','tryBuyItem','undoLastPurchase','reset_game_state','start_level','finish_level_intro','show_confirm_exit_dialog']){const native=window[name];window[name]=function(...args){const r=native.apply(this,args);sync();return r}}
 const nativeInput=handleInput;handleInput=function(x,y){const r=canvas.getBoundingClientRect();x=(x-r.left)*canvas.width/r.width;y=(y-r.top)*canvas.height/r.height;sync();let i=-1;if(gameState==='SETTINGS'){const start=(SCREEN_HEIGHT-550)/2+130;for(let n=0;n<7;n++)if(y>=start+n*60-40&&y<=start+n*60+10)i=n}if(i>=0)adapter.align('SETTINGS:'+i);const result=nativeInput(x,y);sync();return result};
 function paused(index){return adapter.active&&adapter.getState().braked&&menu_selected_index===index}
 function ring(){if(!adapter.active||!adapter.getState().braked)return;const i=menu_selected_index;let r;if(gameState==='BUY')r=[...buy_rects,...buy_buttons_rects].find(x=>x.index===i);else if(gameState==='MENU'){const sz=Math.min(50,SCREEN_WIDTH/12);r={x:SCREEN_WIDTH*.12,y:SCREEN_HEIGHT*.45+i*sz*1.5-sz*1.3,w:SCREEN_WIDTH*.76,h:sz*1.65}}else if(gameState==='SETTINGS')r={x:SCREEN_WIDTH/2-Math.min(600,SCREEN_WIDTH*.95)/2+24,y:(SCREEN_HEIGHT-550)/2+130+i*60-36,w:Math.min(600,SCREEN_WIDTH*.95)-48,h:48};else if(gameState==='PAUSED')r={x:SCREEN_WIDTH/2-Math.min(450,SCREEN_WIDTH*.9)/2+22,y:(SCREEN_HEIGHT-450)/2+140+i*70-36,w:Math.min(450,SCREEN_WIDTH*.9)-44,h:48};else if(gameState==='INSTRUCTIONS'){const h=Math.min(600,SCREEN_HEIGHT*.8);r={x:SCREEN_WIDTH/2-100,y:(SCREEN_HEIGHT-h)/2+h-80,w:200,h:60}}else if(gameState==='CONFIRM_EXIT'){const w=Math.min(600,SCREEN_WIDTH*.9);r={x:SCREEN_WIDTH/2-(w*.8)/2+i*w*.45,y:(SCREEN_HEIGHT-300)/2+200,w:w*.35,h:60}}if(r){ctx.save();ctx.strokeStyle=gameState==='MENU'?'#ffd54f':'#2e7d32';ctx.lineWidth=4;ctx.setLineDash([0,10]);ctx.lineCap='round';ctx.strokeRect(r.x,r.y,r.w,r.h);ctx.restore();canvas.dataset.pausedOutline='dotted'}}
 for(const name of ['draw_main_menu','draw_instructions','draw_pause_menu','draw_settings_menu','draw_buy_menu','draw_confirm_exit']){const native=window[name];window[name]=function(...args){const r=native.apply(this,args);ring();return r}}
 window.classicChoiceDown=e=>{if(!['Space','Enter','NumpadEnter'].includes(e.code))return false;if(e.repeat)return true;sync();if(e.code==='Space'){heldSpace=true;braking=!!adapter.brakePress();if(braking){e.preventDefault();adapter.setInputHeld(heldEnter);return true}}else heldEnter=true;adapter.setInputHeld(heldEnter||heldSpace);return false};
 window.classicChoiceUp=e=>{if(!['Space','Enter','NumpadEnter'].includes(e.code))return false;if(e.code==='Space'){heldSpace=false;if(braking||cancelSpace){if(braking)adapter.brakeRelease();braking=cancelSpace=false;keysPressed.Space=false;clearTimeout(spaceHoldTimeout);spaceHoldTimeout=null;stopBackwardScan();adapter.setInputHeld(heldEnter);return true}}else heldEnter=false;adapter.setInputHeld(heldEnter||heldSpace);return false};
 function cancel(){heldSpace=heldEnter=braking=cancelSpace=false;keysPressed.Space=keysPressed.Enter=false;clearTimeout(spaceHoldTimeout);clearTimeout(enterHoldTimeout);spaceHoldTimeout=enterHoldTimeout=null;stopBackwardScan();adapter.cancelInput()}
 NarbeScanManager.subscribe(next=>{if(next.autoScan!==lastAuto&&heldSpace&&!braking){cancelSpace=true;clearTimeout(spaceHoldTimeout);spaceHoldTimeout=null;stopBackwardScan()}lastAuto=next.autoScan;sync()});window.addEventListener('blur',cancel);document.addEventListener('narbe-input-cancelled',cancel);window.classicChoice={getState:()=>adapter.getState(),getItems:()=>adapter.context?.items.map(x=>({id:x.id,label:x.label}))||[],sync,paused};sync();
})();
