// Shared menu and board hierarchy; fleet rules, turn exchange and native holds remain local.
(function(){
 const wrapHost=document.createElement('div'),status=document.createElement('div'),label=document.createElement('div');wrapHost.id='classic-scan-status';wrapHost.hidden=true;wrapHost.style.cssText='width:100%;grid-column:1/-1;flex-shrink:0;text-align:center';label.style.fontWeight='bold';wrapHost.append(status,label);const css=document.createElement('style');css.textContent='#classic-scan-status[hidden]{display:none!important}[data-narbe-scan-paused],body[data-choice-state="paused"] .row-highlight,body[data-choice-state="paused"] .scan-highlight{outline:3px dotted var(--highlight-color,#ffd700)!important}.classic-fit-board{grid-template-rows:repeat(11,minmax(0,1fr))}.classic-fit-board .grid-cell,.classic-fit-board .grid-label{font-size:min(clamp(.7rem,2vw,1.4rem),calc(var(--classic-board-height) / 12));line-height:1;min-height:0}';document.head.append(css);
 const rawSpeak=speak,rawSelect=selectCurrentItem;const rawPaint={'main-menu':highlightMainMenuButton,'settings-menu':highlightSettingsButton,buttons:highlightMenuButton,ships:highlightShip,modal:highlightModalButton,row:highlightRow,cell:highlightCell,'game-row':highlightGameRow,'game-cell':highlightGameCell,'game-over':highlightGameOverButton,pause:highlightPauseButton,'pause-settings':highlightPauseSettingsButton,cover:highlightCoverButton};
 const lists={'main-menu':['mainMenuButtons',updateMainMenuButtonsList],'settings-menu':['settingsButtons',updateSettingsButtonsList],buttons:['menuButtons',updateMenuButtonsList],ships:['shipButtons',buildShipScanList],modal:['modalButtons',updateModalButtonsList],'game-over':['gameOverButtons',updateGameOverButtonsList],pause:['pauseButtons',updatePauseButtonsList],'pause-settings':['pauseSettingsButtons',updatePauseSettingsButtonsList],cover:['coverButtons',()=>{}]};
 let adapter,syncing=false,heldSpace=false,heldEnter=false,braking=false,cancelSpace=false,lastAuto=NarbeScanManager.getSettings().autoScan,shipReturn=null;
 function describe(){if(!placementBoard||document.getElementById('gameOverModal')?.style.display==='flex')return null;const mode=scanState.mode;if(gameStarted&&(gamePhase==='defense'||awaitingEnemy)&&!['pause','pause-settings','cover','game-over'].includes(mode))return null;let parent,items;const board=mode.startsWith('game-')?attackGrid:placementBoard;const cell=(r,c)=>board?.querySelector('.grid-cell[data-row="'+r+'"][data-col="'+c+'"]');let key=mode+':'+currentPlayer;if(['row','cell'].includes(mode))key+=':'+currentShipIndex;if(['cell','game-cell'].includes(mode))key+=':'+scanState.rowIndex;
  if(mode==='row'||mode==='game-row'){items=letters.flatMap((x,index)=>mode==='game-row'&&isRowFullyFired(index)?[]:[{id:'row:'+index,label:'Row '+x,index,element:cell(index,0),labelElement:label,virtual:true}]);parent=board?.parentElement}
  else if(mode==='cell'||mode==='game-cell'){items=numbers.flatMap((x,index)=>mode==='game-cell'&&isCellAlreadyFired(scanState.rowIndex,index)?[]:[{id:'cell:'+scanState.rowIndex+':'+index,label:getCellLabel(scanState.rowIndex,index),index,element:cell(scanState.rowIndex,index),labelElement:label,virtual:true}]);parent=board?.parentElement}
  else if(lists[mode]){const [field,update]=lists[mode];update();items=(scanState[field]||[]).filter(x=>!x.element?.disabled).map((x,index)=>({id:x.element?.id||x.ship?.id||x.action||mode+':'+index,label:x.element?.textContent?.trim()||x.label,index:scanState[field].indexOf(x),element:x.element||(x.ship?.coords?.length?cell(x.ship.coords[0].row,x.ship.coords[0].col):placementBoard),labelElement:x.element?undefined:label,virtual:!x.element}));const parents={'main-menu':'mainMenuContainer','settings-menu':'settingsContainer',buttons:'placementBoardCard',ships:'placementBoardCard',modal:'shipActionModal','game-over':'gameOverModal',pause:'pauseMainView','pause-settings':'pauseSettingsView',cover:'coverScreen'};parent=document.getElementById(parents[mode]);if(parent?.classList.contains('modal-overlay'))parent=parent.querySelector('.modal-content')||parent.firstElementChild}
  if(['buttons','ships','row','cell'].includes(mode))parent=document.querySelector('#placementScreen .game-header');else if(['game-row','game-cell'].includes(mode))parent=document.querySelector('#attackPhaseScreen .phase-header');
  if(!parent||!items)return null;if(wrapHost.parentElement!==parent){if(board?.parentElement===parent)parent.insertBefore(wrapHost,board);else parent.prepend(wrapHost)}return{key,mode,row:scanState.rowIndex,statusHost:status,items}}
 function fitBoards(show,mode){for(const grid of [placementBoard,attackGrid]){if(!grid)continue;const selected=show&&((grid===placementBoard&&['buttons','ships','row','cell'].includes(mode))||(grid===attackGrid&&['game-row','game-cell'].includes(mode)));grid.classList.toggle('classic-fit-board',selected);if(!selected){grid.style.height='';grid.style.removeProperty('--classic-board-height');continue}const area=grid===placementBoard?grid.parentElement:grid.closest('.phase-content');const st=getComputedStyle(area);let available=area.clientHeight-parseFloat(st.paddingTop)-parseFloat(st.paddingBottom);for(const child of area.children){if(child===grid||child.contains(grid))continue;const cs=getComputedStyle(child);available-=child.getBoundingClientRect().height+(parseFloat(cs.marginTop)||0)+(parseFloat(cs.marginBottom)||0)}grid.style.height=Math.max(60,available-8)+'px';grid.style.setProperty('--classic-board-height',grid.style.height)}}
 function sync(){if(syncing)return;syncing=true;try{const d=describe();adapter.setInputHeld(heldEnter||heldSpace&&!braking);const old=adapter.context;if(d&&old&&old.key!==d.key&&((old.mode==='row'&&d.mode==='cell')||(old.mode==='game-row'&&d.mode==='game-cell'))){adapter.enterGroup(d)}else if(d&&old&&old.key!==d.key&&adapter.getState().depth>0&&((old.mode==='cell'&&d.mode==='row')||(old.mode==='game-cell'&&d.mode==='game-row'))){adapter.back({restore:true});adapter.sync(d)}else adapter.sync(d);if(!d){wrapHost.hidden=true;fitBoards(false)}}finally{syncing=false}}
 adapter=NarbeChoiceScanAdapter.create({holdThreshold:config.longPress,stateHost:document.body,speak:rawSpeak,onContext(c){scanState.mode=c.mode;if(c.mode==='cell'||c.mode==='game-cell')scanState.rowIndex=c.row},onHighlight(item,s,c){const index=item?.index??-1;if(c.mode==='row'||c.mode==='game-row')scanState.rowIndex=index;else if(c.mode==='cell'||c.mode==='game-cell')scanState.cellIndex=index;else scanState.scanIndex=index;clearAllHighlights();if(index>=0)rawPaint[c.mode]?.();wrapHost.hidden=!(s.parked);label.hidden=true;label.textContent=item?.virtual?item.label:'';fitBoards(s.parked,c.mode);if(s.index<0&&document.activeElement?.matches('button,.grid-cell'))document.activeElement.blur()},onSelect(){rawSelect();sync()}});
 for(const name of ['renderBoards','renderAttackGrid','showMainMenu','showSettings','showGame','showPlacementScreen','randomizeAllShips','startGame','switchToAttackPhase','switchToDefensePhase','showCoverScreen','onCoverReady','showShipActionModal','hideShipActionModal','moveFromModal','rotateFromModal','showPauseModal','hidePauseModal','showSettingsFromPause','goBackToPauseMenu','goBackFromSettings','showGameOverModal','returnToMainMenu','updateSettingsDisplay','updatePauseSettingsDisplay','enterShipSelectionMode','enterRowScanMode','handleEscapeKey','handleEnterLongPress','fireAtCurrentCell']){const native=window[name];window[name]=function(...args){const r=native.apply(this,args);sync();return r}}
 startAutoScan=stopAutoScan=restartAutoScan=function(){clearInterval(scanState.autoScanTimer);scanState.autoScanTimer=null;sync()};scanForward=()=>{sync();adapter.step(1)};scanBackward=()=>{sync();adapter.step(-1)};selectCurrentItem=()=>{sync();adapter.select()};speak=text=>{sync();return adapter.active?adapter.announce(text):rawSpeak(text)};
 const rawDown=handleKeyDown,rawUp=handleKeyUp;handleKeyDown=function(e){if(!['Space','Enter','NumpadEnter'].includes(e.code))return rawDown(e);if(e.repeat)return;sync();if(e.code==='Space'){heldSpace=true;braking=!!adapter.brakePress();if(braking){e.preventDefault();adapter.setInputHeld(heldEnter);return}}else heldEnter=true;adapter.setInputHeld(heldEnter||heldSpace);rawDown(e)};handleKeyUp=function(e){if(e.code==='Space'){heldSpace=false;if(braking||cancelSpace){if(braking)adapter.brakeRelease();braking=cancelSpace=false;scanState.spaceHeld=false;clearTimeout(scanState.spaceTimer);clearInterval(scanState.spaceRepeatInterval);scanState.spaceTimer=scanState.spaceRepeatInterval=null;adapter.setInputHeld(heldEnter);return}}else if(e.code==='Enter'||e.code==='NumpadEnter')heldEnter=false;adapter.setInputHeld(heldEnter||heldSpace);rawUp(e);sync()};
 function cancel(){heldSpace=heldEnter=braking=cancelSpace=false;scanState.spaceHeld=scanState.enterHeld=scanState.enterLongTriggered=false;clearTimeout(scanState.spaceTimer);clearTimeout(scanState.enterTimer);clearInterval(scanState.spaceRepeatInterval);scanState.spaceTimer=scanState.enterTimer=scanState.spaceRepeatInterval=null;adapter.cancelInput()}
 NarbeScanManager.subscribe(next=>{if(next.autoScan!==lastAuto&&heldSpace&&!braking){cancelSpace=true;clearTimeout(scanState.spaceTimer);clearInterval(scanState.spaceRepeatInterval);scanState.spaceTimer=scanState.spaceRepeatInterval=null}lastAuto=next.autoScan;sync()});window.addEventListener('blur',cancel);window.addEventListener('resize',sync);document.addEventListener('narbe-input-cancelled',cancel);document.addEventListener('click',e=>{const el=e.target.closest('button');if(!el)return;sync();const item=adapter.context?.items.find(x=>x.element===el);if(item)adapter.align(item.id);queueMicrotask(sync)},true);
 window.classicChoice={getState:()=>adapter.getState(),getItems:()=>adapter.context?.items.map(x=>({id:x.id,label:x.label}))||[],sync};
})();
