// Shared menu/card scan hierarchy. Reveal, memory countdown and turn delays stay native.
(function(){
 const rawSpeak=speak,rawGameSelect=selectGameOption,rawMenuSelect=selectMenuOption,rawPauseSelect=selectPauseOption,rawCardPaint=updateScanHighlight;let adapter,syncing=false,heldSpace=false,heldEnter=false,braking=false,cancelSpace=false,lastAuto=NarbeScanManager.getSettings().autoScan,version=0;
 const wrap=document.createElement('div'),status=document.createElement('div'),label=document.createElement('div');wrap.id='classic-scan-status';wrap.hidden=true;wrap.style.cssText='width:100%;flex-shrink:0;grid-column:1/-1;text-align:center';wrap.append(status,label);const css=document.createElement('style');css.textContent='#classic-scan-status[hidden]{display:none!important}[data-narbe-scan-paused],.classic-row-paused{outline:3px dotted #ffd700!important;border-style:dotted!important}';document.head.append(css);
 function clean(x){const el=document.createElement('div');el.innerHTML=String(typeof x==='function'?x():x);return el.textContent.trim()}
 function describe(){let key,items,parent,phase;if(state.mode==='game'){if(state.busy||!document.getElementById('grid-container'))return null;phase=state.scan.mode;key='game:'+version+':'+state.turn+':'+phase+(phase==='col'?':'+state.scan.row:'');parent=document.getElementById('main-content');if(phase==='row')items=Array.from({length:state.rows},(_,r)=>r).filter(rowHasUnmatched).map(row=>({id:'row:'+row,label:settings.ttsLocation?'Row '+(row+1):'',row,element:document.getElementById('btn-'+row+'-'+state.grid.find(c=>c.r===row&&!c.inactive&&!c.matched&&!c.revealed)?.c),labelElement:label,virtual:true}));else items=state.grid.filter(c=>c.r===state.scan.row&&!c.inactive&&!c.matched&&!c.revealed).map(c=>({id:'card:'+c.r+':'+c.c,label:settings.ttsLocation?'Card '+(c.c+1):'',row:c.r,col:c.c,element:document.getElementById('btn-'+c.r+'-'+c.c),labelElement:label,virtual:true}))}else if(state.mode==='menu'||state.mode==='pause'){const sub=state.mode==='menu'?state.menuState:state.pauseMenuState;key=state.mode+':'+sub;parent=document.getElementById(state.mode==='menu'?'main-content':'pause-overlay');const native=state.mode==='menu'?menus[sub]:sub==='settings'?menus.pauseSettings:menus.pause;if(!parent||!native)return null;const buttons=[...parent.querySelectorAll('.menu-button')];items=native.map((x,index)=>({id:key+':'+clean(x.text).split(':')[0],label:()=>clean(x.tts||x.text),element:buttons[index],index}))}else return null;if(wrap.parentElement!==parent){const first=parent.querySelector('#grid-container,.menu-grid,.setup-layout,.menu-button');first?parent.insertBefore(wrap,first):parent.prepend(wrap)}return{key,mode:state.mode,phase,row:state.scan.row,statusHost:status,items}}
 function sync(options){if(syncing)return;syncing=true;try{const d=describe(),old=adapter.context;adapter.setInputHeld(heldEnter||heldSpace&&!braking);if(d&&old&&old.key!==d.key&&old.mode==='game'&&d.mode==='game'&&old.phase==='row'&&d.phase==='col')adapter.enterGroup(d);else if(d&&old&&old.key!==d.key&&old.mode==='game'&&d.mode==='game'&&old.phase==='col'&&d.phase==='row'&&adapter.getState().depth){adapter.back({restore:true});adapter.sync(d)}else adapter.sync(d,options);if(!d)wrap.hidden=true;decorate()}finally{syncing=false}}
 function decorate(){for(const item of adapter.context?.items||[]){const el=item.element;if(item.virtual||!el||el.dataset.choiceBound)continue;const native=el.onclick;if(!native)continue;el.dataset.choiceBound='true';el.onclick=function(e){sync();adapter.align(item.id);const r=native.call(this,e);sync();return r}}}
 adapter=NarbeChoiceScanAdapter.create({holdThreshold:config.longPress,stateHost:document.body,speak:rawSpeak,onContext(c){if(c.mode==='game'){state.scan.mode=c.phase;if(c.phase==='col')state.scan.row=c.row}},onHighlight(item,s,c){if(c.mode==='game'){if(c.phase==='row')state.scan.row=item?.row??-1;else state.scan.col=item?.col??-1;rawCardPaint();document.querySelectorAll('.classic-row-paused').forEach(e=>e.classList.remove('classic-row-paused'));if(s.braked&&item&&c.phase==='row')for(const cell of state.grid.filter(x=>x.r===item.row&&!x.inactive&&!x.matched&&!x.revealed))document.getElementById('btn-'+cell.r+'-'+cell.c)?.classList.add('classic-row-paused')}else{if(c.mode==='menu')state.menuIndex=item?.index??-1;else state.pauseIndex=item?.index??-1;const parent=document.getElementById(c.mode==='menu'?'main-content':'pause-overlay');for(const el of parent?.querySelectorAll('.menu-button')||[]){el.classList.toggle('active',el===item?.element);el===item?.element?applyActiveStyle(el):removeActiveStyle(el)}}wrap.hidden=!(s.parked);label.hidden=true;label.textContent=item?.virtual?(item.label||'Selected '+(c.phase==='row'?'row':'card')):'';const grid=document.getElementById('grid-container');if(grid){const base=window.innerHeight-(state.gameMode==='challenge'?140:80);grid.style.height=Math.max(100,base-(wrap.hidden||c.mode!=='game'?0:wrap.offsetHeight))+'px'}if(s.index<0&&document.activeElement?.matches('button,.card-button'))document.activeElement.blur()},onSelect(_item,_s,c){syncing=true;try{if(c.mode==='menu')rawMenuSelect();else if(c.mode==='pause')rawPauseSelect();else rawGameSelect()}finally{syncing=false}sync()}});
 for(const name of ['renderMenu','renderPauseMenu','renderGame','updateCardVisual','showMainMenu','showSinglePlayerMenu','showTwoPlayerMenu','showSettingsMenu','showEditorWarning','showLoadWarning','showSetupMenu','updateSetupMenu','resumeGame','revealCard','handleResize','gameOverChallenge','showWinMessage','showMatchWinner']){const native=window[name];window[name]=function(...args){const result=native.apply(this,args);sync();return result}}
 const rawPause=showPauseMenu;showPauseMenu=function(){const r=rawPause();sync({fresh:true});return r};const rawStart=startGame;startGame=function(...args){version++;const r=rawStart.apply(this,args);sync();return r};
 startAutoScan=stopAutoScan=function(){clearInterval(state.timers.scan);state.timers.scan=null;sync()};const step=dir=>{sync();adapter.step(dir)};onSpaceShortPress=()=>step(1);performBackwardScan=()=>step(-1);moveMenuScan=movePauseScan=moveGameScan=step;onEnterShortPress=()=>{sync();adapter.select()};speak=text=>{sync();return adapter.active?adapter.announce(text):rawSpeak(text)};
 window.classicChoiceDown=e=>{if(!['Space','Enter','NumpadEnter'].includes(e.code))return false;if(e.repeat)return true;sync();if(e.code==='Space'){heldSpace=true;braking=!!adapter.brakePress();if(braking){e.preventDefault();adapter.setInputHeld(heldEnter);return true}}else heldEnter=true;adapter.setInputHeld(heldEnter||heldSpace);return false};window.classicChoiceUp=e=>{if(!['Space','Enter','NumpadEnter'].includes(e.code))return false;if(e.code==='Space'){heldSpace=false;if(braking||cancelSpace){if(braking)adapter.brakeRelease();braking=cancelSpace=false;state.input.spaceHeld=state.input.spaceLongPressFired=false;clearTimeout(state.timers.space);clearInterval(state.timers.spaceRepeat);adapter.setInputHeld(heldEnter);return true}}else heldEnter=false;adapter.setInputHeld(heldEnter||heldSpace);return false};
 function cancel(){heldSpace=heldEnter=braking=cancelSpace=false;state.input.spaceHeld=state.input.enterHeld=state.input.spaceLongPressFired=state.input.enterLongPressFired=false;for(const k of ['space','enter','spaceRepeat','enterRepeat']){clearTimeout(state.timers[k]);clearInterval(state.timers[k]);state.timers[k]=null}adapter.cancelInput()}
 NarbeScanManager.subscribe(next=>{if(next.autoScan!==lastAuto&&heldSpace&&!braking){cancelSpace=true;clearTimeout(state.timers.space);clearInterval(state.timers.spaceRepeat)}lastAuto=next.autoScan;sync()});window.addEventListener('blur',cancel);document.addEventListener('narbe-input-cancelled',cancel);window.classicChoice={getState:()=>adapter.getState(),getItems:()=>adapter.context?.items.map(x=>({id:x.id,label:typeof x.label==='function'?x.label():x.label}))||[],sync};
})();
