// Menus and stationary spin decisions share policy; reel and bonus timing stays native.
(function(){
 const status=document.createElement('div');status.id='classic-scan-status';status.hidden=true;status.style.cssText='width:100%;flex-shrink:0;grid-column:1/-1';const style=document.createElement('style');style.textContent='#classic-scan-status[hidden]{display:none!important}[data-narbe-scan-paused]{outline-style:dotted!important}';document.head.append(style);
 const rawSpeak=speak,rawSelect=selectItem,rawHighlight=updateHighlights;let adapter,syncing=false,braking=false,cancelSpace=false,heldSpace=false,heldEnter=false,lastAuto=NarbeScanManager.getSettings().autoScan;
 const field={menu:'menuIndex',pause:'pauseIndex',gameover:'gameoverIndex','autoplay-menu':'autoplayMenuIndex',game:'scanIndex'};
 const gameIds=['spin-button','bet-decrease','bet-increase','bet-max','autoplay-button','pause-scan-button'];
 function describe(){let key=state.mode,items,parent;if(state.mode==='game'){if(state.bonusMode)return null;parent=document.getElementById('game-container-inner');items=gameIds.map((id,nativeIndex)=>({id,label:['Spin','Decrease Bet','Increase Bet','Max Bet',state.autoplayActive?'Stop Autoplay':'Autoplay','Pause'][nativeIndex],element:document.getElementById(id),nativeIndex})).filter(x=>!state.spinning||x.nativeIndex===5)}else if(state.mode==='autoplay-menu'){parent=document.getElementById('pause-overlay');items=[...autoplayOptions.map((x,i)=>({id:'btn-autoplay-'+i,label:x.label,nativeIndex:i})),{id:'btn-autoplay-cancel',label:'Cancel',nativeIndex:autoplayOptions.length}].map(x=>({...x,element:document.getElementById(x.id)}))}else{const sub=state.mode==='menu'?state.menuState:state.mode==='pause'?state.pauseMenuState:state.mode;key+=':'+sub;const native=state.mode==='menu'?menus[sub]:state.mode==='pause'?sub==='settings'?menus.pauseSettings:menus.pause:state.mode==='gameover'?menus.gameover:null;if(!native)return null;parent=document.getElementById(state.mode==='menu'?'menu-container':'pause-overlay');items=native.map((x,nativeIndex)=>({id:key+':'+nativeIndex,label:()=>{const el=document.createElement('div');el.innerHTML=typeof x.text==='function'?x.text():x.text;return el.textContent.trim()},element:document.getElementById('btn-'+parent.id+'-'+nativeIndex),nativeIndex}))}if(!parent)return null;if(status.parentElement!==parent){const first=parent.querySelector('.menu-grid,.menu-button,#game-actions');first?parent.insertBefore(status,first):parent.prepend(status)}return{key,items,statusHost:status}}
 function sync(options){if(syncing)return;syncing=true;try{const d=describe();adapter.setInputHeld(heldEnter||heldSpace&&!braking);adapter.sync(d,options);if(!d)status.hidden=true;decorate()}finally{syncing=false}}
 function decorate(){for(const x of adapter.context?.items||[]){const el=x.element;if(!el||el.dataset.choiceBound)continue;const native=el.onclick;if(!native)continue;el.dataset.choiceBound='true';el.onclick=function(e){sync();adapter.align(x.id);const result=native.call(this,e);sync();return result}}}
 adapter=NarbeChoiceScanAdapter.create({holdThreshold:config.longPress,stateHost:document.body,speak:rawSpeak,onHighlight(item,s){state[field[state.mode]]=item?.nativeIndex??-1;status.hidden=!(s.parked);rawHighlight();if(s.index<0&&document.activeElement?.matches('button'))document.activeElement.blur()},onSelect(){rawSelect();sync()}});
 for(const name of ['renderMenu','showMainMenu','showSettingsMenu','showPauseMenu','showPauseSettings','showGameOver','refreshMenu','refreshPauseMenu','startGame','resumeGame','updateGameUI','showAutoplayMenu','startAutoplay','stopAutoplay','doSpin','evaluateResults','triggerDiamondBonus','endBonusMode']){const native=window[name];window[name]=function(...args){const r=native.apply(this,args);sync();return r}}
 const close=closeAutoplayMenu;closeAutoplayMenu=function(){const r=close();sync({fresh:true,restoreId:'autoplay-button'});return r};
 startAutoScan=stopAutoScan=resetAutoScan=function(){clearInterval(state.timers.autoScan);state.timers.autoScan=null;sync()};scanForward=()=>{sync();adapter.step(1)};scanBackward=()=>{sync();adapter.step(-1)};selectItem=()=>{sync();adapter.select()};speak=text=>{sync();return adapter.active?adapter.announce(text):rawSpeak(text)};
 window.classicChoiceDown=function(e){if(!['Space','Enter','NumpadEnter'].includes(e.code))return false;if(e.repeat)return true;sync();if(e.code==='Space'){heldSpace=true;braking=!!adapter.brakePress();if(braking){e.preventDefault();adapter.setInputHeld(heldEnter);return true}}else heldEnter=true;adapter.setInputHeld(heldEnter||heldSpace);return false};
 window.classicChoiceUp=function(e){if(!['Space','Enter','NumpadEnter'].includes(e.code))return false;if(e.code==='Space'){heldSpace=false;if(braking||cancelSpace){e.preventDefault();if(braking)adapter.brakeRelease();braking=cancelSpace=false;state.input.spaceHeld=false;clearTimeout(state.timers.space);stopBackwardsScan();adapter.setInputHeld(heldEnter);return true}}else heldEnter=false;adapter.setInputHeld(heldEnter||heldSpace);return false};
 function cancel(){heldSpace=heldEnter=braking=cancelSpace=false;state.input.spaceHeld=state.input.enterHeld=false;for(const k of ['space','enter','spaceRepeat','enterRepeat']){clearTimeout(state.timers[k]);clearInterval(state.timers[k]);state.timers[k]=null}adapter.cancelInput()}
 NarbeScanManager.subscribe(next=>{if(next.autoScan!==lastAuto&&heldSpace&&!braking){cancelSpace=true;clearTimeout(state.timers.space);stopBackwardsScan()}lastAuto=next.autoScan;sync()});window.addEventListener('blur',cancel);document.addEventListener('narbe-input-cancelled',cancel);window.classicChoice={getState:()=>adapter.getState(),getItems:()=>adapter.context?.items.map(x=>({id:x.id,label:typeof x.label==='function'?x.label():x.label}))||[],sync};
})();
