// Menu-only shared scanner. Continuous aim, held power and ten-second pause remain native.
(function(){
 const status=document.createElement('div');status.id='classic-scan-status';status.hidden=true;status.style.cssText='width:100%;flex-shrink:0';const css=document.createElement('style');css.textContent='#classic-scan-status[hidden]{display:none!important}[data-narbe-scan-paused]{outline-style:dotted!important}';document.head.append(css);
 const rawVisual=MenuSystem.prototype.updateVisuals,rawSelect=MenuSystem.prototype.selectCurrent,rawSpeak=audio.speak.bind(audio);let adapter,syncing=false,heldSpace=false,heldEnter=false,braking=false,cancelSpace=false,lastAuto=NarbeScanManager.getSettings().autoScan;
 function sync(options){if(syncing)return;syncing=true;try{const menu=MenuManager.currentMenu;let d=null;if((gameState==='MENU'||gameState==='PAUSED')&&menu&&menu.getClientRects().length){if(status.parentElement!==menu.parentElement)menu.parentElement.insertBefore(status,menu);d={key:menu.id,statusHost:status,items:[...menu.querySelectorAll('.menu-item')].map((element,nativeIndex)=>({id:element.dataset.action,label:element.textContent.trim(),element,nativeIndex}))}}adapter.setInputHeld(heldEnter||heldSpace&&!braking);adapter.sync(d,options);if(!d)status.hidden=true}finally{syncing=false}}
 adapter=NarbeChoiceScanAdapter.create({holdThreshold:3000,stateHost:document.body,speak:text=>NarbeVoiceManager.speak(text),onHighlight(item,s){MenuManager.activeIndex=item?.nativeIndex??-1;rawVisual.call(MenuManager);status.hidden=!(s.parked);if(s.index<0&&document.activeElement?.matches('.menu-item'))document.activeElement.blur()},onSelect(){rawSelect.call(MenuManager);sync()}});
 for(const name of ['init','refreshSettingsMenu','setActiveMenu','handleAction','togglePause']){const native=MenuSystem.prototype[name];MenuSystem.prototype[name]=function(...args){const result=native.apply(this,args);sync(name==='setActiveMenu'?{fresh:true}:undefined);return result}};
 MenuSystem.prototype.startAutoScan=MenuSystem.prototype.stopAutoScan=function(){clearInterval(this.autoScanTimer);this.autoScanTimer=null;sync()};MenuSystem.prototype.scanNext=()=>{sync();adapter.step(1)};MenuSystem.prototype.scanPrev=()=>{sync();adapter.step(-1)};MenuSystem.prototype.selectCurrent=()=>{sync();adapter.select()};
 MenuSystem.prototype.updateVisuals=function(){if(!syncing&&this.currentMenu&&this.activeIndex>=0){const el=this.currentMenu.querySelectorAll('.menu-item')[this.activeIndex];sync();if(el)adapter.align(el.dataset.action)}else rawVisual.call(this)};
 MenuSystem.prototype.speakSelection=function(){sync();adapter.announce()};audio.speak=function(text){sync();return adapter.active?adapter.announce(text):rawSpeak(text)};
 for(const name of ['setupRound','gameOver']){const native=window[name];window[name]=function(...args){const result=native.apply(this,args);sync();return result}}
 const down=InputHandler.prototype.handleKeyDown,up=InputHandler.prototype.handleKeyUp;const normal=e=>e.code==='NumpadEnter'?{code:'Enter',repeat:e.repeat,preventDefault:()=>e.preventDefault()}:e;
 InputHandler.prototype.handleKeyDown=function(event){const e=normal(event);if(!['Space','Enter'].includes(e.code))return down.call(this,e);if(e.repeat)return;e.preventDefault();sync();if(e.code==='Space'){heldSpace=true;braking=!!adapter.brakePress();if(braking){adapter.setInputHeld(heldEnter);return}}else heldEnter=true;adapter.setInputHeld(heldEnter||heldSpace);down.call(this,e);sync()};
 InputHandler.prototype.handleKeyUp=function(event){const e=normal(event);if(!['Space','Enter'].includes(e.code))return up.call(this,e);e.preventDefault();if(e.code==='Space'){heldSpace=false;if(braking||cancelSpace){if(braking)adapter.brakeRelease();braking=cancelSpace=false;this.spacePressed=false;clearTimeout(this.spaceLongPressTimer);this.stopBackwardScan();adapter.setInputHeld(heldEnter);return}}else heldEnter=false;adapter.setInputHeld(heldEnter||heldSpace);up.call(this,e);sync()};
 function cancel(){heldSpace=heldEnter=braking=cancelSpace=false;Input.spacePressed=Input.enterPressed=false;clearTimeout(Input.spaceLongPressTimer);clearTimeout(Input.enterLongPressTimer);Input.stopBackwardScan();aimActive=false;adapter.cancelInput()}
 NarbeScanManager.subscribe(next=>{if(next.autoScan!==lastAuto&&heldSpace&&!braking){cancelSpace=true;clearTimeout(Input.spaceLongPressTimer);Input.stopBackwardScan()}lastAuto=next.autoScan;sync()});window.addEventListener('blur',cancel);document.addEventListener('narbe-input-cancelled',cancel);window.classicChoice={getState:()=>adapter.getState(),getItems:()=>adapter.context?.items.map(x=>({id:x.id,label:x.label}))||[],sync};
})();
